version: '3.8'

services:

  web:
    build: .
    ports:
      - 8000:8000
    command: poetry run python -m app.main
    volumes:
      - ./persistent_data:/BigId/persistent_data
    environment:
      - APP_PORT = 8000
      - APP_HOST = 0.0.0.0
      - LOGGER_NAME = app.loger
      - DATABASE_URL = sqlite+aiosqlite:///./persistent_data/bigid.db
      - CELERY_RESULT_BACKEND = redis://localhost:6379
      - CELERY_BROKER_URL = redis://localhost:6379
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"  
    restart: always